[build]
publish = "public"
command = """\
  curl -LJO https://github.com/sass/dart-sass/releases/download/1.84.0/dart-sass-1.84.0-linux-x64.tar.gz && \
  tar -xf dart-sass-1.84.0-linux-x64.tar.gz && \
  rm dart-sass-1.84.0-linux-x64.tar.gz && \
  export PATH=/opt/build/repo/dart-sass:$PATH && \
  make production-build \
  """

[build.environment]
HUGO_VERSION = "0.143.0"
GO_VERSION = "1.24"
DART_SASS_VERSION = "1.84.0"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
