[build]
publish = "public"
command = "make production-build"

[build.environment]
HUGO_VERSION = "0.143.0"
GO_VERSION = "1.24"

[context.deploy-preview]
command = "make preview-build"

[context.branch-deploy]
command = "make preview-build"
