on:
  push:
    branches:
      - dead-links
  pull_request:
  workflow_dispatch:
name: Link Chack
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JustinBeckwith/linkinator-action@v1
        with:
          linksToSkip: "http://localhost:1313"
