# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  pull_request:
  
  push:
    branches:
      - 'next'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: read
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

# Default to bash
defaults:
  run:
    shell: bash

env:
  HUGO_VERSION: 0.139.0
  HUGO_ENVIRONMENT: production
  NETLIFY_SITE_NAME: bucolic-gaufre-15c8dc
  DART_SASS_VERSION: 1.81.0

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Hugo CLI
        run: sudo snap install hugo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        run: |
          hugo \
            --minify \
            --baseURL "${{ env.NETLIFY_SITE_ID }}.netlify.app" \
            --buildFuture \
            --disableKinds="robotsTXT"
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: ./public

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v3.0
        with:
          # Publish directory
          publish-dir: './public'
          # Functions directory
          functions-dir: # optional
          # Custom deploy message for Netlify
          deploy-message: # optional
          # GitHub token
          github-token: # optional
          # Production branch
          production-branch: # optional
          # Indicate whether to deploy production build
          production-deploy: # optional
          # Enable pull request comment
          enable-pull-request-comment: # optional
          # Enable commit comment
          enable-commit-comment: # optional
          # Enable GitHub commit status
          enable-commit-status: # optional
          # Overwrites pull request comment
          overwrites-pull-request-comment: # optional
          # Path to netlify.toml
          netlify-config-path: './netlify.toml'
          # Specifies the prefix for the deployment URL
          alias: # optional
          # Whether or not to deploy to GitHub
          enable-github-deployment: # optional
          # Environment name of GitHub Deployments
          github-deployment-environment: 'Netlify'
          # Description of the GitHub Deployment
          github-deployment-description: # optional
          # Fails if no credentials provided
          fails-without-credentials: # optional

